[package]
name = "parallel-programming"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "pthreads"
path = "src/lib.rs"

[[bin]]
name = "chap2"
path = "src/chap2.rs"
