all: ex2211 ex2212 cas spinlock mutex semaphore posix_semaphore

ex2211: ex2211.c

ex2212: ex2212.c

cas: cas.c

spinlock: spinlock.c

mutex: mutex.c

semaphore: semaphore.c

posix_semaphore: posix_semaphore.c

